
const Sdata = {
  shopItems: [
    {
      id: 2,
      discount: 15,
      cover: "./images/Esenciales/flash-2.png",
      name: "Frost Cat Indoor 7.5kg + Obsequio",
      price: 1950,
      type: ["Comida"],
    },
    {
      id: 3,
      discount: 40,
      cover: "./images/Esenciales/flash-3.png",
      name: "Equilibrio perro adulto 18kg + obsequio",
      price: 2990,
      type: ["Comida"],
    },
    {
      id: 4,
      discount: 20,
      cover: "./images/Esenciales/flash-4.png",
      name: "Rascador de gato 2 niveles con cama 70cm",
      price: 1790,
      type: ["Juguetes", "Para la Casa"],
    },
    {
      id: 5,
      discount: 10,
      cover: "./images/Esenciales/flash-5.png",
      name: "Bandeja Sanitaria Para Gato Con Borde Extraíble Y Pala",
      price: 520,
      type: ["Para la casa", "Cuidado"],
    },
    {
      id: 6,
      discount: 10,
      cover: "./images/Esenciales/flash-1.png",
      name: "Platos Comida 30cm para perro/gato",
      price: 349,
      type: ["Comida", "Para la Casa"],
    },
    {
      id: 7,
      cover: "./images/arrivals/arrivals1.png",
      name: "Bebedero De Agua Inteligente Xiaomi Para Mascotas Amv",
      price: "2.598",
      type: ["Comida", "Para la Casa"],
    },
    {
      id: 8,
      cover: "./images/arrivals/arrivals2.png",
      name: "Cuna Cama Cucha Mascota Perro Gato Rectangular 50 X 37 Atrix",
      price: "347",
      type: ["Para la Casa"],
    },
    {
      id: 9,
      cover: "./images/arrivals/arrivals3.png",
      name: "3 Tabletas Antipulgas Y Garrapatas Simparica De 20 A 40 Kg",
      price: "1.220",
      type: ["Cuidado", "Para la Casa"],
    },
    {
      id: 10,
      cover: "./images/arrivals/arrivals4.png",
      name: "Guante Cepillo Saca Quita Pelos Para Perros Gatos Mascotas",
      price: "80",
      type: ["Cuidado"],
    },
    {
      id: 11,
      cover: "./images/arrivals/arrivals5.png",
      name: "Pañales/sabanillas De Entrenamiento Perro X 50 Unid",
      price: "1.195",
      type: ["Cuidado"],
    },
    {
      id: 12,
      cover: "./images/arrivals/arrivals6.png",
      name: "Pala Higiénica Levanta Desechos De Mascotas Grande Oferta",
      price: "350",
      type: ["Paseo"],
    },
    {
      id: 13,
      cover: "./images/arrivals/arrivals7.png",
      name: "Pipeta Anti Pulgas Y Garrapatas Dominal Max Gatos Mas De 4kg",
      price: "244",
      type: ["Cuidado"],
    },
  ],
}
export default Sdata
